version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk
    steps:
      - checkout
      - run:
          name: Build Artifact
          command: |
            cd webapp
            pwd
            sudo apt install maven
            mvn clean package -DskipTests
            cd target
            ls -al
            cd ../..
            pwd
      - run:
          name: Zip Artifact
          command: |
            echo "Hello the current build number is ${CIRCLE_BUILD_NUM}"
            pwd
            ls -al
            mkdir -p lambda_artifact
            pwd
            ls -al
            zip -r csye6225-webapp_lambda.zip webapp/target/webapp-1.0-SNAPSHOT.jar
            ls -al
            mv csye6225-webapp_lambda.zip lambda_artifact/
            cd lambda_artifact
            ls -al
            pwd
            cd ..
            pwd
            ls -al
      - run:
          name: Install AWS CLI & Build Artifact
          command: |
            sudo apt-get update || sudo apt-get update
            sudo apt-get install python3
            python3 --version
            sudo apt install python3-pip
            pip3 --version
            sudo pip3 install awscli
      - run:
          name: Upload Lambda Artifact to S3
          command: |
            cd lambda_artifact
            aws s3 cp csye6225-webapp_lambda.zip s3://${bucketName}
      - run:
          name: AWS Lambda Update Function Code
          command: |
            echo "Hello AWS Lambda Update Function Code"
            aws lambda update-function-code --function-name MyLambdaFunction --region ${AWS_REGION} 
            echo "code deployment complete"